export const CRAFT_BRANCHES = {
  "Warrior": {
    "Swords": [
      "MAIN_SWORD",
      "2H_CLAYMORE",
      "2H_DUALSWORD",
      "MAIN_SCIMITAR_MORGANA",
      "2H_CLEAVER_HELL",
      "2H_DUALSCIMITAR_UNDEAD",
      "2H_CLAYMORE_AVALON"
    ],
    "Axes": [
      "MAIN_AXE",
      "2H_AXE",
      "2H_HALBERD",
      "2H_HALBERD_MORGANA",
      "2H_SCYTHE_HELL",
      "2H_DUALAXE_KEEPER",
      "2H_AXE_AVALON"
    ],
    "Maces": [
      "MAIN_MACE",
      "2H_MACE",
      "2H_FLAIL",
      "MAIN_ROCKMACE_KEEPER",
      "MAIN_MACE_HELL",
      "2H_MACE_MORGANA",
      "2H_DUALMACE_AVALON"
    ],
    "Hammers": [
      "MAIN_HAMMER",
      "2H_POLEHAMMER",
      "2H_HAMMER",
      "2H_HAMMER_UNDEAD",
      "2H_DUALHAMMER_HELL",
      "2H_RAM_KEEPER",
      "2H_HAMMER_AVALON"
    ],
    "Crossbows": [
      "2H_CROSSBOW",
      "2H_CROSSBOWLARGE",
      "MAIN_1HCROSSBOW",
      "2H_REPEATINGCROSSBOW_UNDEAD",
      "2H_CROSSBOWLARGE_MORGANA",
      "2H_CROSSBOW_CANNON_AVALON"
    ],
    "Shields": [
      "OFF_SHIELD",
      "OFF_TOWERSHIELD_UNDEAD",
      "OFF_SHIELD_HELL",
      "OFF_SPIKEDSHIELD_MORGANA",
      "OFF_SHIELD_AVALON"
    ],
    "Plate Armor": [
      "ARMOR_PLATE_SET1",
      "ARMOR_PLATE_SET2",
      "ARMOR_PLATE_SET3",
      "ARMOR_PLATE_UNDEAD",
      "ARMOR_PLATE_HELL",
      "ARMOR_PLATE_KEEPER",
      "ARMOR_PLATE_AVALON"
    ],
    "Plate Helmet": [
      "HEAD_PLATE_SET1",
      "HEAD_PLATE_SET2",
      "HEAD_PLATE_SET3",
      "HEAD_PLATE_UNDEAD",
      "HEAD_PLATE_HELL",
      "HEAD_PLATE_KEEPER",
      "HEAD_PLATE_AVALON"
    ],
    "Plate Shoes": [
      "SHOES_PLATE_SET1",
      "SHOES_PLATE_SET2",
      "SHOES_PLATE_SET3",
      "SHOES_PLATE_UNDEAD",
      "SHOES_PLATE_HELL",
      "SHOES_PLATE_KEEPER",
      "SHOES_PLATE_AVALON"
    ]
  },
  "Hunter": {
    "Bows": [
      "2H_BOW",
      "2H_WARBOW",
      "2H_LONGBOW",
      "2H_LONGBOW_UNDEAD",
      "2H_BOW_HELL",
      "2H_BOW_KEEPER",
      "2H_BOW_AVALON"
    ],
    "Spears": [
      "MAIN_SPEAR",
      "2H_SPEAR",
      "2H_GLAIVE",
      "MAIN_SPEAR_KEEPER",
      "2H_HARPOON_HELL",
      "2H_TRIDENT_UNDEAD"
    ],
    "Nature Staffs": [
      "MAIN_NATURESTAFF",
      "2H_NATURESTAFF",
      "2H_WILDSTAFF",
      "MAIN_NATURESTAFF_KEEPER",
      "2H_NATURESTAFF_HELL"
    ],
    "Daggers": [
      "MAIN_DAGGER",
      "2H_DAGGERPAIR",
      "2H_CLAWPAIR",
      "MAIN_DAGGER_HELL",
      "2H_IRONGAUNTLETS_HELL",
      "2H_DUALSICKLE_UNDEAD"
    ],
    "Quarterstaffs": [
      "2H_QUARTERSTAFF",
      "2H_IRONCLADEDSTAFF",
      "2H_DOUBLEBLADEDSTAFF",
      "2H_COMBATSTAFF_MORGANA",
      "2H_TWINSCYTHE_HELL",
      "2H_ROCKSTAFF_KEEPER",
      "2H_QUARTERSTAFF_AVALON"
    ],
    "Torches": [
      "OFF_TORCH",
      "OFF_HORN_KEEPER",
      "OFF_TALISMAN_AVALON",
      "OFF_LAMP_UNDEAD",
      "OFF_JESTERCANE_HELL"
    ],
    "Leather Armor": [
      "ARMOR_LEATHER_SET1",
      "ARMOR_LEATHER_SET2",
      "ARMOR_LEATHER_SET3",
      "ARMOR_LEATHER_UNDEAD",
      "ARMOR_LEATHER_HELL",
      "ARMOR_LEATHER_MORGANA",
      "ARMOR_LEATHER_AVALON"
    ],
    "Leather Helmet": [
      "HEAD_LEATHER_SET1",
      "HEAD_LEATHER_SET2",
      "HEAD_LEATHER_SET3",
      "HEAD_LEATHER_UNDEAD",
      "HEAD_LEATHER_HELL",
      "HEAD_LEATHER_MORGANA",
      "HEAD_LEATHER_AVALON"
    ],
    "Leather Shoes": [
      "SHOES_LEATHER_SET1",
      "SHOES_LEATHER_SET2",
      "SHOES_LEATHER_SET3",
      "SHOES_LEATHER_UNDEAD",
      "SHOES_LEATHER_HELL",
      "SHOES_LEATHER_MORGANA",
      "SHOES_LEATHER_AVALON"
    ]
  },
  "Mage": {
    "Fire Staffs": [
      "MAIN_FIRESTAFF",
      "2H_FIRESTAFF",
      "2H_INFERNOSTAFF",
      "MAIN_FIRESTAFF_KEEPER",
      "2H_FIRESTAFF_HELL"
    ],
    "Holy Staffs": [
      "MAIN_HOLYSTAFF",
      "2H_HOLYSTAFF",
      "2H_DIVINESTAFF",
      "MAIN_HOLYSTAFF_MORGANA",
      "2H_HOLYSTAFF_HELL",
      "2H_HOLYSTAFF_UNDEAD",
      "MAIN_HOLYSTAFF_AVALON"
    ],
    "Arcane Staffs": [
      "MAIN_ARCANESTAFF",
      "2H_ARCANESTAFF",
      "2H_ENIGMATICSTAFF",
      "MAIN_ARCANESTAFF_UNDEAD",
      "2H_ARCANESTAFF_HELL",
      "2H_ENIGMATICORB_MORGANA"
    ],
    "Frost Staffs": [
      "MAIN_FROSTSTAFF",
      "2H_FROSTSTAFF",
      "2H_GLACIALSTAFF",
      "MAIN_FROSTSTAFF_KEEPER",
      "2H_ICEGAUNTLETS_HELL",
      "MAIN_FROSTSTAFF_AVALON"
    ],
    "Cursed Staffs": [
      "MAIN_CURSEDSTAFF",
      "2H_CURSEDSTAFF",
      "2H_DEMONICSTAFF",
      "MAIN_CURSEDSTAFF_UNDEAD",
      "2H_SKULLORB_HELL",
      "2H_CURSEDSTAFF_MORGANA"
    ],
    "Tomes": [
      "OFF_BOOK",
      "OFF_ORB_MORGANA",
      "OFF_DEMONSKULL_HELL",
      "OFF_TOTEM_KEEPER",
      "OFF_CENSER_AVALON"
    ],
    "Cloth Armor": [
      "ARMOR_CLOTH_SET1",
      "ARMOR_CLOTH_SET2",
      "ARMOR_CLOTH_SET3",
      "ARMOR_CLOTH_HELL",
      "ARMOR_CLOTH_KEEPER",
      "ARMOR_CLOTH_AVALON"
    ],
    "Cloth Helmet": [
      "HEAD_CLOTH_SET1",
      "HEAD_CLOTH_SET2",
      "HEAD_CLOTH_SET3",
      "HEAD_CLOTH_HELL",
      "HEAD_CLOTH_KEEPER",
      "HEAD_CLOTH_AVALON"
    ],
    "Cloth Shoes": [
      "SHOES_CLOTH_SET1",
      "SHOES_CLOTH_SET2",
      "SHOES_CLOTH_SET3",
      "SHOES_CLOTH_HELL",
      "SHOES_CLOTH_KEEPER",
      "SHOES_CLOTH_AVALON"
    ]
  },
  "Toolmaker": {
    "Accessories": [
      "BAG",
      "CAPE",
      "CAPEITEM_UNDEAD",
      "CAPEITEM_KEEPER",
      "CAPEITEM_MORGANA",
      "CAPEITEM_DEMON",
      "CAPEITEM_FW_BRIDGEWATCH",
      "CAPEITEM_FW_CAERLEON",
      "CAPEITEM_FW_FORTSTERLING",
      "CAPEITEM_FW_LYMHURST",
      "CAPEITEM_FW_MARTLOCK",
      "CAPEITEM_FW_THETFORD",
      "CAPEITEM_HERETIC"
    ]
  }
};

export const RECIPES = {
  'OFF_SHIELD': { itemSuffix: 'OFF_SHIELD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'METALBAR': 4}, nutrition: 42.9, journal: 'WARRIOR' },
  'OFF_TOWERSHIELD_UNDEAD': { itemSuffix: 'OFF_TOWERSHIELD_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'METALBAR': 4, 'ARTEFACT_OFF_TOWERSHIELD_UNDEAD': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'OFF_SHIELD_HELL': { itemSuffix: 'OFF_SHIELD_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'METALBAR': 4, 'ARTEFACT_OFF_SHIELD_HELL': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'OFF_SPIKEDSHIELD_MORGANA': { itemSuffix: 'OFF_SPIKEDSHIELD_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'METALBAR': 4, 'ARTEFACT_OFF_SPIKEDSHIELD_MORGANA': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'OFF_SHIELD_AVALON': { itemSuffix: 'OFF_SHIELD_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'METALBAR': 4, 'ARTEFACT_OFF_SHIELD_AVALON': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'OFF_BOOK': { itemSuffix: 'OFF_BOOK', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 4, 'LEATHER': 4}, nutrition: 42.9, journal: 'MAGE' },
  'OFF_ORB_MORGANA': { itemSuffix: 'OFF_ORB_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 4, 'LEATHER': 4, 'ARTEFACT_OFF_ORB_MORGANA': 1}, nutrition: 42.9, journal: 'MAGE' },
  'OFF_DEMONSKULL_HELL': { itemSuffix: 'OFF_DEMONSKULL_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 4, 'LEATHER': 4, 'ARTEFACT_OFF_DEMONSKULL_HELL': 1}, nutrition: 42.9, journal: 'MAGE' },
  'OFF_TOTEM_KEEPER': { itemSuffix: 'OFF_TOTEM_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 4, 'LEATHER': 4, 'ARTEFACT_OFF_TOTEM_KEEPER': 1}, nutrition: 42.9, journal: 'MAGE' },
  'OFF_CENSER_AVALON': { itemSuffix: 'OFF_CENSER_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 4, 'LEATHER': 4, 'ARTEFACT_OFF_CENSER_AVALON': 1}, nutrition: 42.9, journal: 'MAGE' },
  'OFF_TORCH': { itemSuffix: 'OFF_TORCH', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'CLOTH': 4}, nutrition: 42.9, journal: 'HUNTER' },
  'OFF_HORN_KEEPER': { itemSuffix: 'OFF_HORN_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'CLOTH': 4, 'ARTEFACT_OFF_HORN_KEEPER': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'OFF_TALISMAN_AVALON': { itemSuffix: 'OFF_TALISMAN_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'CLOTH': 4, 'ARTEFACT_OFF_TALISMAN_AVALON': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'OFF_LAMP_UNDEAD': { itemSuffix: 'OFF_LAMP_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'CLOTH': 4, 'ARTEFACT_OFF_LAMP_UNDEAD': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'OFF_JESTERCANE_HELL': { itemSuffix: 'OFF_JESTERCANE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 4, 'CLOTH': 4, 'ARTEFACT_OFF_JESTERCANE_HELL': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'CAPE': { itemSuffix: 'CAPE', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 4, 'LEATHER': 4}, nutrition: 42.9, journal: 'TOOLMAKER' },
  'CAPEITEM_FW_BRIDGEWATCH': { itemSuffix: 'CAPEITEM_FW_BRIDGEWATCH', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_FW_BRIDGEWATCH_BP': 1, 'T1_FACTION_STEPPE_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_FW_FORTSTERLING': { itemSuffix: 'CAPEITEM_FW_FORTSTERLING', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_FW_FORTSTERLING_BP': 1, 'T1_FACTION_MOUNTAIN_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_FW_LYMHURST': { itemSuffix: 'CAPEITEM_FW_LYMHURST', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_FW_LYMHURST_BP': 1, 'T1_FACTION_FOREST_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_FW_MARTLOCK': { itemSuffix: 'CAPEITEM_FW_MARTLOCK', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_FW_MARTLOCK_BP': 1, 'T1_FACTION_HIGHLAND_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_FW_THETFORD': { itemSuffix: 'CAPEITEM_FW_THETFORD', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_FW_THETFORD_BP': 1, 'T1_FACTION_SWAMP_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_FW_CAERLEON': { itemSuffix: 'CAPEITEM_FW_CAERLEON', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_FW_CAERLEON_BP': 1, 'T1_FACTION_CAERLEON_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_HERETIC': { itemSuffix: 'CAPEITEM_HERETIC', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_HERETIC_BP': 1, 'T1_FACTION_FOREST_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_UNDEAD': { itemSuffix: 'CAPEITEM_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_UNDEAD_BP': 1, 'T1_FACTION_MOUNTAIN_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_KEEPER': { itemSuffix: 'CAPEITEM_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_KEEPER_BP': 1, 'T1_FACTION_HIGHLAND_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_MORGANA': { itemSuffix: 'CAPEITEM_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_MORGANA_BP': 1, 'T1_FACTION_SWAMP_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'CAPEITEM_DEMON': { itemSuffix: 'CAPEITEM_DEMON', tiers: [4, 5, 6, 7, 8], ingredients: {'CAPE': 1, 'CAPEITEM_DEMON_BP': 1, 'T1_FACTION_STEPPE_TOKEN_1': 1}, nutrition: 0.0, journal: 'TOOLMAKER' },
  'BAG': { itemSuffix: 'BAG', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'LEATHER': 8}, nutrition: 85.8, journal: 'TOOLMAKER' },
  'HEAD_PLATE_SET1': { itemSuffix: 'HEAD_PLATE_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_SET1': { itemSuffix: 'ARMOR_PLATE_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_SET1': { itemSuffix: 'SHOES_PLATE_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_PLATE_SET2': { itemSuffix: 'HEAD_PLATE_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_SET2': { itemSuffix: 'ARMOR_PLATE_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_SET2': { itemSuffix: 'SHOES_PLATE_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_PLATE_SET3': { itemSuffix: 'HEAD_PLATE_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_SET3': { itemSuffix: 'ARMOR_PLATE_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_SET3': { itemSuffix: 'SHOES_PLATE_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_PLATE_UNDEAD': { itemSuffix: 'HEAD_PLATE_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_HEAD_PLATE_UNDEAD': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_UNDEAD': { itemSuffix: 'ARMOR_PLATE_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'ARTEFACT_ARMOR_PLATE_UNDEAD': 1}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_UNDEAD': { itemSuffix: 'SHOES_PLATE_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_SHOES_PLATE_UNDEAD': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_PLATE_HELL': { itemSuffix: 'HEAD_PLATE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_HEAD_PLATE_HELL': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_HELL': { itemSuffix: 'ARMOR_PLATE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'ARTEFACT_ARMOR_PLATE_HELL': 1}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_HELL': { itemSuffix: 'SHOES_PLATE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_SHOES_PLATE_HELL': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_PLATE_KEEPER': { itemSuffix: 'HEAD_PLATE_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_HEAD_PLATE_KEEPER': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_KEEPER': { itemSuffix: 'ARMOR_PLATE_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'ARTEFACT_ARMOR_PLATE_KEEPER': 1}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_KEEPER': { itemSuffix: 'SHOES_PLATE_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_SHOES_PLATE_KEEPER': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_PLATE_AVALON': { itemSuffix: 'HEAD_PLATE_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_HEAD_PLATE_AVALON': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'ARMOR_PLATE_AVALON': { itemSuffix: 'ARMOR_PLATE_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'ARTEFACT_ARMOR_PLATE_AVALON': 1}, nutrition: 85.8, journal: 'WARRIOR' },
  'SHOES_PLATE_AVALON': { itemSuffix: 'SHOES_PLATE_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 8, 'ARTEFACT_SHOES_PLATE_AVALON': 1}, nutrition: 42.9, journal: 'WARRIOR' },
  'HEAD_LEATHER_SET1': { itemSuffix: 'HEAD_LEATHER_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_SET1': { itemSuffix: 'ARMOR_LEATHER_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_SET1': { itemSuffix: 'SHOES_LEATHER_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_LEATHER_SET2': { itemSuffix: 'HEAD_LEATHER_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_SET2': { itemSuffix: 'ARMOR_LEATHER_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_SET2': { itemSuffix: 'SHOES_LEATHER_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_LEATHER_SET3': { itemSuffix: 'HEAD_LEATHER_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_SET3': { itemSuffix: 'ARMOR_LEATHER_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_SET3': { itemSuffix: 'SHOES_LEATHER_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_LEATHER_MORGANA': { itemSuffix: 'HEAD_LEATHER_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_HEAD_LEATHER_MORGANA': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_MORGANA': { itemSuffix: 'ARMOR_LEATHER_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16, 'ARTEFACT_ARMOR_LEATHER_MORGANA': 1}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_MORGANA': { itemSuffix: 'SHOES_LEATHER_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_SHOES_LEATHER_MORGANA': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_LEATHER_HELL': { itemSuffix: 'HEAD_LEATHER_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_HEAD_LEATHER_HELL': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_HELL': { itemSuffix: 'ARMOR_LEATHER_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16, 'ARTEFACT_ARMOR_LEATHER_HELL': 1}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_HELL': { itemSuffix: 'SHOES_LEATHER_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_SHOES_LEATHER_HELL': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_LEATHER_UNDEAD': { itemSuffix: 'HEAD_LEATHER_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_HEAD_LEATHER_UNDEAD': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_UNDEAD': { itemSuffix: 'ARMOR_LEATHER_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16, 'ARTEFACT_ARMOR_LEATHER_UNDEAD': 1}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_UNDEAD': { itemSuffix: 'SHOES_LEATHER_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_SHOES_LEATHER_UNDEAD': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_LEATHER_AVALON': { itemSuffix: 'HEAD_LEATHER_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_HEAD_LEATHER_AVALON': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'ARMOR_LEATHER_AVALON': { itemSuffix: 'ARMOR_LEATHER_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 16, 'ARTEFACT_ARMOR_LEATHER_AVALON': 1}, nutrition: 85.8, journal: 'HUNTER' },
  'SHOES_LEATHER_AVALON': { itemSuffix: 'SHOES_LEATHER_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'LEATHER': 8, 'ARTEFACT_SHOES_LEATHER_AVALON': 1}, nutrition: 42.9, journal: 'HUNTER' },
  'HEAD_CLOTH_SET1': { itemSuffix: 'HEAD_CLOTH_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8}, nutrition: 42.9, journal: 'MAGE' },
  'ARMOR_CLOTH_SET1': { itemSuffix: 'ARMOR_CLOTH_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 16}, nutrition: 85.8, journal: 'MAGE' },
  'SHOES_CLOTH_SET1': { itemSuffix: 'SHOES_CLOTH_SET1', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8}, nutrition: 42.9, journal: 'MAGE' },
  'HEAD_CLOTH_SET2': { itemSuffix: 'HEAD_CLOTH_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8}, nutrition: 42.9, journal: 'MAGE' },
  'ARMOR_CLOTH_SET2': { itemSuffix: 'ARMOR_CLOTH_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 16}, nutrition: 85.8, journal: 'MAGE' },
  'SHOES_CLOTH_SET2': { itemSuffix: 'SHOES_CLOTH_SET2', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8}, nutrition: 42.9, journal: 'MAGE' },
  'HEAD_CLOTH_SET3': { itemSuffix: 'HEAD_CLOTH_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8}, nutrition: 42.9, journal: 'MAGE' },
  'ARMOR_CLOTH_SET3': { itemSuffix: 'ARMOR_CLOTH_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 16}, nutrition: 85.8, journal: 'MAGE' },
  'SHOES_CLOTH_SET3': { itemSuffix: 'SHOES_CLOTH_SET3', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8}, nutrition: 42.9, journal: 'MAGE' },
  'HEAD_CLOTH_KEEPER': { itemSuffix: 'HEAD_CLOTH_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'ARTEFACT_HEAD_CLOTH_KEEPER': 1}, nutrition: 42.9, journal: 'MAGE' },
  'ARMOR_CLOTH_KEEPER': { itemSuffix: 'ARMOR_CLOTH_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 16, 'ARTEFACT_ARMOR_CLOTH_KEEPER': 1}, nutrition: 85.8, journal: 'MAGE' },
  'SHOES_CLOTH_KEEPER': { itemSuffix: 'SHOES_CLOTH_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'ARTEFACT_SHOES_CLOTH_KEEPER': 1}, nutrition: 42.9, journal: 'MAGE' },
  'HEAD_CLOTH_HELL': { itemSuffix: 'HEAD_CLOTH_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'ARTEFACT_HEAD_CLOTH_HELL': 1}, nutrition: 42.9, journal: 'MAGE' },
  'ARMOR_CLOTH_HELL': { itemSuffix: 'ARMOR_CLOTH_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 16, 'ARTEFACT_ARMOR_CLOTH_HELL': 1}, nutrition: 85.8, journal: 'MAGE' },
  'SHOES_CLOTH_HELL': { itemSuffix: 'SHOES_CLOTH_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'ARTEFACT_SHOES_CLOTH_HELL': 1}, nutrition: 42.9, journal: 'MAGE' },
  'HEAD_CLOTH_AVALON': { itemSuffix: 'HEAD_CLOTH_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'ARTEFACT_HEAD_CLOTH_AVALON': 1}, nutrition: 42.9, journal: 'MAGE' },
  'ARMOR_CLOTH_AVALON': { itemSuffix: 'ARMOR_CLOTH_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 16, 'ARTEFACT_ARMOR_CLOTH_AVALON': 1}, nutrition: 85.8, journal: 'MAGE' },
  'SHOES_CLOTH_AVALON': { itemSuffix: 'SHOES_CLOTH_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'CLOTH': 8, 'ARTEFACT_SHOES_CLOTH_AVALON': 1}, nutrition: 42.9, journal: 'MAGE' },
  '2H_BOW': { itemSuffix: '2H_BOW', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_WARBOW': { itemSuffix: '2H_WARBOW', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_LONGBOW': { itemSuffix: '2H_LONGBOW', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_LONGBOW_UNDEAD': { itemSuffix: '2H_LONGBOW_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32, 'ARTEFACT_2H_LONGBOW_UNDEAD': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_BOW_HELL': { itemSuffix: '2H_BOW_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32, 'ARTEFACT_2H_BOW_HELL': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_BOW_KEEPER': { itemSuffix: '2H_BOW_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32, 'ARTEFACT_2H_BOW_KEEPER': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_BOW_AVALON': { itemSuffix: '2H_BOW_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 32, 'ARTEFACT_2H_BOW_AVALON': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_CROSSBOW': { itemSuffix: '2H_CROSSBOW', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_CROSSBOWLARGE': { itemSuffix: '2H_CROSSBOWLARGE', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  'MAIN_1HCROSSBOW': { itemSuffix: 'MAIN_1HCROSSBOW', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_REPEATINGCROSSBOW_UNDEAD': { itemSuffix: '2H_REPEATINGCROSSBOW_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_CROSSBOWLARGE_MORGANA': { itemSuffix: '2H_CROSSBOWLARGE_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_CROSSBOWLARGE_MORGANA': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_CROSSBOW_CANNON_AVALON': { itemSuffix: '2H_CROSSBOW_CANNON_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_CROSSBOW_CANNON_AVALON': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  'MAIN_CURSEDSTAFF': { itemSuffix: 'MAIN_CURSEDSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8}, nutrition: 128.6, journal: 'MAGE' },
  '2H_CURSEDSTAFF': { itemSuffix: '2H_CURSEDSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  '2H_DEMONICSTAFF': { itemSuffix: '2H_DEMONICSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_CURSEDSTAFF_UNDEAD': { itemSuffix: 'MAIN_CURSEDSTAFF_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8, 'ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD': 1}, nutrition: 128.6, journal: 'MAGE' },
  '2H_SKULLORB_HELL': { itemSuffix: '2H_SKULLORB_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_SKULLORB_HELL': 1}, nutrition: 171.5, journal: 'MAGE' },
  '2H_CURSEDSTAFF_MORGANA': { itemSuffix: '2H_CURSEDSTAFF_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_CURSEDSTAFF_MORGANA': 1}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_FIRESTAFF': { itemSuffix: 'MAIN_FIRESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8}, nutrition: 128.6, journal: 'MAGE' },
  '2H_FIRESTAFF': { itemSuffix: '2H_FIRESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  '2H_INFERNOSTAFF': { itemSuffix: '2H_INFERNOSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_FIRESTAFF_KEEPER': { itemSuffix: 'MAIN_FIRESTAFF_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8, 'ARTEFACT_MAIN_FIRESTAFF_KEEPER': 1}, nutrition: 128.6, journal: 'MAGE' },
  '2H_FIRESTAFF_HELL': { itemSuffix: '2H_FIRESTAFF_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_FIRESTAFF_HELL': 1}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_FROSTSTAFF': { itemSuffix: 'MAIN_FROSTSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8}, nutrition: 128.6, journal: 'MAGE' },
  '2H_FROSTSTAFF': { itemSuffix: '2H_FROSTSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  '2H_GLACIALSTAFF': { itemSuffix: '2H_GLACIALSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_FROSTSTAFF_KEEPER': { itemSuffix: 'MAIN_FROSTSTAFF_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8, 'ARTEFACT_MAIN_FROSTSTAFF_KEEPER': 1}, nutrition: 128.6, journal: 'MAGE' },
  '2H_ICEGAUNTLETS_HELL': { itemSuffix: '2H_ICEGAUNTLETS_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_ICEGAUNTLETS_HELL': 1}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_FROSTSTAFF_AVALON': { itemSuffix: 'MAIN_FROSTSTAFF_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8, 'ARTEFACT_MAIN_FROSTSTAFF_AVALON': 1}, nutrition: 128.6, journal: 'MAGE' },
  'MAIN_ARCANESTAFF': { itemSuffix: 'MAIN_ARCANESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8}, nutrition: 128.6, journal: 'MAGE' },
  '2H_ARCANESTAFF': { itemSuffix: '2H_ARCANESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  '2H_ENIGMATICSTAFF': { itemSuffix: '2H_ENIGMATICSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_ARCANESTAFF_UNDEAD': { itemSuffix: 'MAIN_ARCANESTAFF_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8, 'ARTEFACT_MAIN_ARCANESTAFF_UNDEAD': 1}, nutrition: 128.6, journal: 'MAGE' },
  '2H_ARCANESTAFF_HELL': { itemSuffix: '2H_ARCANESTAFF_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_ARCANESTAFF_HELL': 1}, nutrition: 171.5, journal: 'MAGE' },
  '2H_ENIGMATICORB_MORGANA': { itemSuffix: '2H_ENIGMATICORB_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_ENIGMATICORB_MORGANA': 1}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_HOLYSTAFF': { itemSuffix: 'MAIN_HOLYSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'CLOTH': 8}, nutrition: 128.6, journal: 'MAGE' },
  '2H_HOLYSTAFF': { itemSuffix: '2H_HOLYSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'MAGE' },
  '2H_DIVINESTAFF': { itemSuffix: '2H_DIVINESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_HOLYSTAFF_MORGANA': { itemSuffix: 'MAIN_HOLYSTAFF_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'CLOTH': 8, 'ARTEFACT_MAIN_HOLYSTAFF_MORGANA': 1}, nutrition: 128.6, journal: 'MAGE' },
  '2H_HOLYSTAFF_HELL': { itemSuffix: '2H_HOLYSTAFF_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12, 'ARTEFACT_2H_HOLYSTAFF_HELL': 1}, nutrition: 171.5, journal: 'MAGE' },
  '2H_HOLYSTAFF_UNDEAD': { itemSuffix: '2H_HOLYSTAFF_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12, 'ARTEFACT_2H_HOLYSTAFF_UNDEAD': 1}, nutrition: 171.5, journal: 'MAGE' },
  'MAIN_HOLYSTAFF_AVALON': { itemSuffix: 'MAIN_HOLYSTAFF_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'CLOTH': 8, 'ARTEFACT_MAIN_HOLYSTAFF_AVALON': 1}, nutrition: 128.6, journal: 'MAGE' },
  'MAIN_NATURESTAFF': { itemSuffix: 'MAIN_NATURESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'CLOTH': 8}, nutrition: 128.6, journal: 'HUNTER' },
  '2H_NATURESTAFF': { itemSuffix: '2H_NATURESTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_WILDSTAFF': { itemSuffix: '2H_WILDSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_NATURESTAFF_KEEPER': { itemSuffix: 'MAIN_NATURESTAFF_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'CLOTH': 8, 'ARTEFACT_MAIN_NATURESTAFF_KEEPER': 1}, nutrition: 128.6, journal: 'HUNTER' },
  '2H_NATURESTAFF_HELL': { itemSuffix: '2H_NATURESTAFF_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'CLOTH': 12, 'ARTEFACT_2H_NATURESTAFF_HELL': 1}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_DAGGER': { itemSuffix: 'MAIN_DAGGER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 12}, nutrition: 128.6, journal: 'HUNTER' },
  '2H_DAGGERPAIR': { itemSuffix: '2H_DAGGERPAIR', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'LEATHER': 16}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_CLAWPAIR': { itemSuffix: '2H_CLAWPAIR', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_DAGGER_HELL': { itemSuffix: 'MAIN_DAGGER_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 12, 'ARTEFACT_MAIN_DAGGER_HELL': 1}, nutrition: 128.6, journal: 'HUNTER' },
  '2H_IRONGAUNTLETS_HELL': { itemSuffix: '2H_IRONGAUNTLETS_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20, 'ARTEFACT_2H_IRONGAUNTLETS_HELL': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_DUALSICKLE_UNDEAD': { itemSuffix: '2H_DUALSICKLE_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'LEATHER': 16, 'ARTEFACT_2H_DUALSICKLE_UNDEAD': 1}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_SPEAR': { itemSuffix: 'MAIN_SPEAR', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8}, nutrition: 128.6, journal: 'HUNTER' },
  '2H_SPEAR': { itemSuffix: '2H_SPEAR', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_GLAIVE': { itemSuffix: '2H_GLAIVE', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 12, 'METALBAR': 20}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_SPEAR_KEEPER': { itemSuffix: 'MAIN_SPEAR_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 16, 'METALBAR': 8, 'ARTEFACT_MAIN_SPEAR_KEEPER': 1}, nutrition: 128.6, journal: 'HUNTER' },
  '2H_HARPOON_HELL': { itemSuffix: '2H_HARPOON_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_HARPOON_HELL': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_TRIDENT_UNDEAD': { itemSuffix: '2H_TRIDENT_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_TRIDENT_UNDEAD': 1}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_AXE': { itemSuffix: 'MAIN_AXE', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 8, 'METALBAR': 16}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_AXE': { itemSuffix: '2H_AXE', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 12, 'METALBAR': 20}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_HALBERD': { itemSuffix: '2H_HALBERD', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_HALBERD_MORGANA': { itemSuffix: '2H_HALBERD_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 20, 'METALBAR': 12, 'ARTEFACT_2H_HALBERD_MORGANA': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_SCYTHE_HELL': { itemSuffix: '2H_SCYTHE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 12, 'METALBAR': 20, 'ARTEFACT_2H_SCYTHE_HELL': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_DUALAXE_KEEPER': { itemSuffix: '2H_DUALAXE_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 12, 'METALBAR': 20, 'ARTEFACT_2H_DUALAXE_KEEPER': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_AXE_AVALON': { itemSuffix: '2H_AXE_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'PLANKS': 12, 'METALBAR': 20, 'ARTEFACT_2H_AXE_AVALON': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  'MAIN_SWORD': { itemSuffix: 'MAIN_SWORD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'LEATHER': 8}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_CLAYMORE': { itemSuffix: '2H_CLAYMORE', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'LEATHER': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_DUALSWORD': { itemSuffix: '2H_DUALSWORD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'LEATHER': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  'MAIN_SCIMITAR_MORGANA': { itemSuffix: 'MAIN_SCIMITAR_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'LEATHER': 8, 'ARTEFACT_MAIN_SCIMITAR_MORGANA': 1}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_CLEAVER_HELL': { itemSuffix: '2H_CLEAVER_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'LEATHER': 12, 'ARTEFACT_2H_CLEAVER_HELL': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_DUALSCIMITAR_UNDEAD': { itemSuffix: '2H_DUALSCIMITAR_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'LEATHER': 12, 'ARTEFACT_2H_DUALSCIMITAR_UNDEAD': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_CLAYMORE_AVALON': { itemSuffix: '2H_CLAYMORE_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'LEATHER': 12, 'ARTEFACT_2H_CLAYMORE_AVALON': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_QUARTERSTAFF': { itemSuffix: '2H_QUARTERSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_IRONCLADEDSTAFF': { itemSuffix: '2H_IRONCLADEDSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_DOUBLEBLADEDSTAFF': { itemSuffix: '2H_DOUBLEBLADEDSTAFF', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_COMBATSTAFF_MORGANA': { itemSuffix: '2H_COMBATSTAFF_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20, 'ARTEFACT_2H_COMBATSTAFF_MORGANA': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_TWINSCYTHE_HELL': { itemSuffix: '2H_TWINSCYTHE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20, 'ARTEFACT_2H_TWINSCYTHE_HELL': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_ROCKSTAFF_KEEPER': { itemSuffix: '2H_ROCKSTAFF_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20, 'ARTEFACT_2H_ROCKSTAFF_KEEPER': 1}, nutrition: 171.5, journal: 'HUNTER' },
  '2H_QUARTERSTAFF_AVALON': { itemSuffix: '2H_QUARTERSTAFF_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 12, 'LEATHER': 20, 'ARTEFACT_2H_QUARTERSTAFF_AVALON': 1}, nutrition: 171.5, journal: 'HUNTER' },
  'MAIN_HAMMER': { itemSuffix: 'MAIN_HAMMER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 24}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_POLEHAMMER': { itemSuffix: '2H_POLEHAMMER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_HAMMER': { itemSuffix: '2H_HAMMER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_HAMMER_UNDEAD': { itemSuffix: '2H_HAMMER_UNDEAD', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12, 'ARTEFACT_2H_HAMMER_UNDEAD': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_DUALHAMMER_HELL': { itemSuffix: '2H_DUALHAMMER_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12, 'ARTEFACT_2H_DUALHAMMER_HELL': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_RAM_KEEPER': { itemSuffix: '2H_RAM_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12, 'ARTEFACT_2H_RAM_KEEPER': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_HAMMER_AVALON': { itemSuffix: '2H_HAMMER_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12, 'ARTEFACT_2H_HAMMER_AVALON': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  'MAIN_MACE': { itemSuffix: 'MAIN_MACE', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'CLOTH': 8}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_MACE': { itemSuffix: '2H_MACE', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_FLAIL': { itemSuffix: '2H_FLAIL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12}, nutrition: 171.5, journal: 'WARRIOR' },
  'MAIN_ROCKMACE_KEEPER': { itemSuffix: 'MAIN_ROCKMACE_KEEPER', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'CLOTH': 8, 'ARTEFACT_MAIN_ROCKMACE_KEEPER': 1}, nutrition: 128.6, journal: 'WARRIOR' },
  'MAIN_MACE_HELL': { itemSuffix: 'MAIN_MACE_HELL', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 16, 'CLOTH': 8, 'ARTEFACT_MAIN_MACE_HELL': 1}, nutrition: 128.6, journal: 'WARRIOR' },
  '2H_MACE_MORGANA': { itemSuffix: '2H_MACE_MORGANA', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12, 'ARTEFACT_2H_MACE_MORGANA': 1}, nutrition: 171.5, journal: 'WARRIOR' },
  '2H_DUALMACE_AVALON': { itemSuffix: '2H_DUALMACE_AVALON', tiers: [4, 5, 6, 7, 8], ingredients: {'METALBAR': 20, 'CLOTH': 12, 'ARTEFACT_2H_DUALMACE_AVALON': 1}, nutrition: 171.5, journal: 'WARRIOR' },
};

export const CITIES = ['Caerleon', 'Bridgewatch', 'Martlock', 'Thetford', 'Fort Sterling', 'Lymhurst', 'Black Market', 'Brecilien'];
